// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRNyxmViUktFLs6PhpeRAHfgzE-OYAU7w',
    appId: '1:689388328534:web:234b024e8b522714c4cdf7',
    messagingSenderId: '689388328534',
    projectId: 'rideshare-b9261',
    authDomain: 'rideshare-b9261.firebaseapp.com',
    storageBucket: 'rideshare-b9261.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr1rK-J9eaG96KHYXnXZG8sLRypiYTNZw',
    appId: '1:689388328534:android:2706f316af08f2eac4cdf7',
    messagingSenderId: '689388328534',
    projectId: 'rideshare-b9261',
    storageBucket: 'rideshare-b9261.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkrbI4Md-vzlBu0HCPghSSlShaW2BX7_s',
    appId: '1:689388328534:ios:ba8ade7be95155e6c4cdf7',
    messagingSenderId: '689388328534',
    projectId: 'rideshare-b9261',
    storageBucket: 'rideshare-b9261.firebasestorage.app',
    iosBundleId: 'com.example.rideshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkrbI4Md-vzlBu0HCPghSSlShaW2BX7_s',
    appId: '1:689388328534:ios:ba8ade7be95155e6c4cdf7',
    messagingSenderId: '689388328534',
    projectId: 'rideshare-b9261',
    storageBucket: 'rideshare-b9261.firebasestorage.app',
    iosBundleId: 'com.example.rideshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRNyxmViUktFLs6PhpeRAHfgzE-OYAU7w',
    appId: '1:689388328534:web:f97ca1d59747c25ec4cdf7',
    messagingSenderId: '689388328534',
    projectId: 'rideshare-b9261',
    authDomain: 'rideshare-b9261.firebaseapp.com',
    storageBucket: 'rideshare-b9261.firebasestorage.app',
  );
}
